In [ ]:
# a) Extraer la información del archivo

import pandas as pd
df = pd.read_csv("country_vaccinations.csv")
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

In [ ]:
# b. Mostrar la estructura y tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas,
#asegurándote que las columnas con fechas sean del tipo datetime64.

df.info()

df["date"] = pd.to_datetime(df["date"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  object
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: float64(9), object(6)
memory usage: 9.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86512 entries, 0 to 86511
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              86512 non-null  object
 1   iso_code                             86512 non-null  object
 2   date                                 86512 non-null  datetime64[ns]
 3   total_vaccinations                   43607 non-null  float64
 4   people_vaccinated                    41294 non-null  float64
 5   people_fully_vaccinated              38802 non-null  float64
 6   daily_vaccinations_raw               35362 non-null  float64
 7   daily_vaccinations                   86213 non-null  float64
 8   total_vaccinations_per_hundred       43607 non-null  float64
 9   people_vaccinated_per_hundred        41294 non-null  float64
 10  people_fully_vaccinated_per_hundred  38802 non-null  float64
 11  daily_vaccinations_per_million       86213 non-null  float64
 12  vaccines                             86512 non-null  object
 13  source_name                          86512 non-null  object
 14  source_website                       86512 non-null  object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 9.9+ MB

In [ ]:
#c. Determinar la cantidad de vacunas aplicadas de cada compañía (con base en cómo lo reporta cada país en la columna vaccines,
#en otras palabras, agrupe por vaccines y realice la sumatoria).


df_sorted = df.sort_values(["country", "date"])
latest = df_sorted.groupby("country", as_index=False).tail(1)

vacunas_por_compania = (
    latest.groupby("vaccines", as_index=False)["total_vaccinations"]
    .sum()
    .sort_values("total_vaccinations", ascending=False)
)

vacunas_por_compania.head(10)

                                             vaccines  total_vaccinations
10  CanSino, Sinopharm/Beijing, Sinopharm/Wuhan, S...        3.263129e+09
16             Covaxin, Oxford/AstraZeneca, Sputnik V        1.834501e+09
50       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech        6.273466e+08
33          Johnson&Johnson, Moderna, Pfizer/BioNTech        5.890990e+08
20  Johnson&Johnson, Moderna, Novavax, Oxford/Astr...        5.055200e+08
24  Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...        4.856527e+08
41  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...        4.168930e+08
21  Johnson&Johnson, Moderna, Novavax, Oxford/Astr...        3.771089e+08
26  Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...        2.436427e+08
5   CanSino, Covaxin, Moderna, Oxford/AstraZeneca,...        2.193686e+08

In [ ]:
# d. Obtener la cantidad de vacunas aplicadas en todo el mundo.
total_vacunas = latest["total_vaccinations"].sum()
total_vacunas

np.float64(11308135686.0)

In [ ]:
# e. Calcular el promedio de vacunas aplicadas por país.

promedio_vacunas = latest["total_vaccinations"].mean()
promedio_vacunas

np.float64(52595979.93488372)

In [ ]:
# f. Determinar la cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo.
fecha_obj = pd.to_datetime("2021-01-29")
total_vacunas_dia = df.loc[df["date"] == fecha_obj, "daily_vaccinations"].sum()
total_vacunas_dia

np.float64(4884052.0)

In [ ]:
#g. Crear un dataframe nuevo denominado conDiferencias que contenga los datos originales y una columna derivada (diferencias)
#con las diferencias de aplicación entre las columnas daily_vaccionations y daily_vaccionations_raw.

conDiferencias = df.copy()

conDiferencias["daily_vaccinations"] = pd.to_numeric(conDiferencias["daily_vaccinations"], errors="coerce")
conDiferencias["daily_vaccinations_raw"] = pd.to_numeric(conDiferencias["daily_vaccinations_raw"], errors="coerce")

conDiferencias["diferencias"] = (
    conDiferencias["daily_vaccinations"] - conDiferencias["daily_vaccinations_raw"]
)

conDiferencias[["country","date","daily_vaccinations","daily_vaccinations_raw","diferencias"]].head()

,country,date,daily_vaccinations,daily_vaccinations_raw,diferencias
0,Afghanistan,2021-02-22,NaN,NaN,NaN
1,Afghanistan,2021-02-23,1367.0,NaN,NaN
2,Afghanistan,2021-02-24,1367.0,NaN,NaN
3,Afghanistan,2021-02-25,1367.0,NaN,NaN
4,Afghanistan,2021-02-26,1367.0,NaN,NaN

In [ ]:
#h. Obtener el periodo de tiempo entre el registro con fecha más reciente y el registro con fecha más antigua.

periodo = df["date"].max() - df["date"].min()
periodo

Timedelta('482 days 00:00:00')

In [ ]:
# i. Crear un dataframe nuevo denominado conCantidad que contenga los datos originales y una columna derivada (canVac)
#con la cantidad de vacunas utilizadas cada día (usar la columna vaccines y separar por el carácter , ).

conCantidad = df.copy()

conCantidad["canVac"] = (
    conCantidad["vaccines"]
    .fillna("")
    .apply(lambda x: len([v.strip() for v in x.split(",") if v.strip()]))
)

conCantidad[["country","date","vaccines","canVac"]].head()

,country,date,vaccines,canVac
0,Afghanistan,2021-02-22,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4
1,Afghanistan,2021-02-23,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4
2,Afghanistan,2021-02-24,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4
3,Afghanistan,2021-02-25,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4
4,Afghanistan,2021-02-26,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",4

In [ ]:
# j. Generar un dataframe denominado antes20 con todos los registros que se hayan realizado antes del 20 de diciembre de 2020.

antes20 = df[df["date"] < pd.to_datetime("2020-12-20")].copy()
antes20.shape

(70, 15)

In [ ]:
# k. Obtener un dataframe denominado pfizer con todos los registros donde se haya utilizado la vacuna Pfizer.

pfizer = df[df["vaccines"].fillna("").str.contains("Pfizer", case=False)].copy()
pfizer.shape

output = "resultadosReto.xlsx"

In [ ]:
# l. Almacenar los dataframes generados (conDiferencias, conCantidad, antes20 y pfizer) en un archivo de Excel denominado resultadosReto.xlsx,
#donde cada dataframe ocupe una hoja diferente. Se recomienda ver la documentación de pd.ExcelWriter.


with pd.ExcelWriter(output, engine="openpyxl") as writer:
    conDiferencias.to_excel(writer, sheet_name="conDiferencias", index=False)
    conCantidad.to_excel(writer, sheet_name="conCantidad", index=False)
    antes20.to_excel(writer, sheet_name="antes20", index=False)
    pfizer.to_excel(writer, sheet_name="pfizer", index=False)

output

'resultadosReto.xlsx'